-- ============================================================================
-- BreastAware — Step 3 database setup  (BA-002, BA-003, BA-019, BA-029/030/031)
-- Paste into: Supabase Dashboard -> SQL Editor -> New query -> Run
-- Safe to re-run (idempotent).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. TABLES  (with foreign keys to auth.users + data-validation constraints)
-- ---------------------------------------------------------------------------

create table if not exists public.ba_profiles (
  id                  bigint generated by default as identity primary key,
  user_id             uuid not null unique references auth.users(id) on delete cascade,
  display_name        text,
  preferred_name      text,
  onboarding_complete boolean not null default false,
  age_range           text,
  timezone            text not null default 'UTC',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table if not exists public.ba_normal_baselines (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null unique references auth.users(id) on delete cascade,
  look_notes        text not null default '',
  feel_notes        text not null default '',
  size_shape_notes  text not null default '',
  texture_notes     text not null default '',
  nipple_notes      text not null default '',
  cycle_notes       text not null default '',
  asymmetry_notes   text not null default '',
  other_notes       text not null default '',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create table if not exists public.ba_observations (
  id                      bigint generated by default as identity primary key,
  user_id                 uuid not null references auth.users(id) on delete cascade,
  observed_at             timestamptz not null default now(),
  change_type             text not null check (change_type in
                            ('lump_or_thickening','skin_change','nipple_change','discharge',
                             'pain_or_tenderness','swelling','shape_change','other')),
  side                    text not null default 'not_specified'
                            check (side in ('left','right','both','not_specified')),
  location_description    text not null default '',
  location_x              numeric,
  location_y              numeric,
  size_description        text not null default '',
  texture                 text not null default '',
  pain_level              integer check (pain_level is null or (pain_level between 0 and 10)),
  duration                text not null default '',
  associated_symptoms     jsonb not null default '[]'::jsonb,
  notes                   text not null default '',
  discussed_with_provider boolean not null default false,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

create table if not exists public.ba_body_map_markers (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  side           text not null default 'front',
  x_pct          numeric not null check (x_pct between 0 and 100),
  y_pct          numeric not null check (y_pct between 0 and 100),
  label          text not null default 'Noted area',
  notes          text not null default '',
  observation_id bigint references public.ba_observations(id) on delete set null,
  created_at     timestamptz not null default now()
);

create table if not exists public.ba_screenings (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  screening_type text not null check (screening_type in
                   ('mammogram','clinical_breast_exam','ultrasound','mri','biopsy','other')),
  facility       text not null default '',
  screening_date date not null,
  result_summary text not null default '',
  next_due_date  date,
  notes          text not null default '',
  created_at     timestamptz not null default now()
);

create table if not exists public.ba_appointments (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references auth.users(id) on delete cascade,
  title            text not null,
  provider_name    text not null default '',
  appointment_date date not null,
  appointment_time text not null default '',
  location         text not null default '',
  notes            text not null default '',
  completed        boolean not null default false,
  created_at       timestamptz not null default now()
);

create table if not exists public.ba_risk_notes (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  category    text not null check (category in
                ('family_history','personal_history','genetic','lifestyle','other')),
  description text not null,
  notes       text not null default '',
  created_at  timestamptz not null default now()
);

create table if not exists public.ba_doctor_prep (
  id                  bigint generated by default as identity primary key,
  user_id             uuid not null references auth.users(id) on delete cascade,
  category            text not null default 'question'
                        check (category in ('question','symptom','history','medication','goal','other')),
  content             text not null,
  is_priority         boolean not null default false,
  included_in_summary boolean not null default true,
  is_complete         boolean not null default false,
  created_at          timestamptz not null default now()
);

create table if not exists public.ba_check_ins (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  check_in_type text not null check (check_in_type in ('no_change','noticed_change','question')),
  notes         text not null default '',
  created_at    timestamptz not null default now()
);

create table if not exists public.ba_vault_documents (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  title         text not null,
  doc_type      text not null default 'other'
                  check (doc_type in ('imaging_report','lab','visit_summary','insurance','other')),
  file_url      text not null default '',
  file_name     text not null default '',
  notes         text not null default '',
  document_date date,
  created_at    timestamptz not null default now()
);

create table if not exists public.ba_education (
  id          bigint generated by default as identity primary key,
  slug        text not null unique,
  title       text not null,
  category    text not null,
  summary     text not null default '',
  body        text not null default '',
  sources     jsonb not null default '[]'::jsonb,
  sort_order  integer not null default 0,
  reviewed_at date,
  version     integer not null default 1,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 2. INDEXES
-- ---------------------------------------------------------------------------
create index if not exists idx_ba_observations_user_date on public.ba_observations (user_id, observed_at desc);
create index if not exists idx_ba_markers_user          on public.ba_body_map_markers (user_id);
create index if not exists idx_ba_screenings_user_date  on public.ba_screenings (user_id, screening_date desc);
create index if not exists idx_ba_appointments_user_date on public.ba_appointments (user_id, appointment_date);
create index if not exists idx_ba_risk_user             on public.ba_risk_notes (user_id);
create index if not exists idx_ba_prep_user             on public.ba_doctor_prep (user_id);
create index if not exists idx_ba_checkins_user         on public.ba_check_ins (user_id, created_at desc);
create index if not exists idx_ba_vault_user            on public.ba_vault_documents (user_id, created_at desc);
create index if not exists idx_ba_education_sort        on public.ba_education (sort_order);

-- ---------------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------
alter table public.ba_profiles          enable row level security;
alter table public.ba_normal_baselines  enable row level security;
alter table public.ba_observations      enable row level security;
alter table public.ba_body_map_markers  enable row level security;
alter table public.ba_screenings        enable row level security;
alter table public.ba_appointments      enable row level security;
alter table public.ba_risk_notes        enable row level security;
alter table public.ba_doctor_prep       enable row level security;
alter table public.ba_check_ins         enable row level security;
alter table public.ba_vault_documents   enable row level security;
alter table public.ba_education         enable row level security;

drop policy if exists "ba_profiles_owner_select" on public.ba_profiles;
drop policy if exists "ba_profiles_owner_insert" on public.ba_profiles;
drop policy if exists "ba_profiles_owner_update" on public.ba_profiles;
drop policy if exists "ba_profiles_owner_delete" on public.ba_profiles;
create policy "ba_profiles_owner_select" on public.ba_profiles for select to authenticated using (auth.uid() = user_id);
create policy "ba_profiles_owner_insert" on public.ba_profiles for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_profiles_owner_update" on public.ba_profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_profiles_owner_delete" on public.ba_profiles for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_normal_baselines_owner_select" on public.ba_normal_baselines;
drop policy if exists "ba_normal_baselines_owner_insert" on public.ba_normal_baselines;
drop policy if exists "ba_normal_baselines_owner_update" on public.ba_normal_baselines;
drop policy if exists "ba_normal_baselines_owner_delete" on public.ba_normal_baselines;
create policy "ba_normal_baselines_owner_select" on public.ba_normal_baselines for select to authenticated using (auth.uid() = user_id);
create policy "ba_normal_baselines_owner_insert" on public.ba_normal_baselines for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_normal_baselines_owner_update" on public.ba_normal_baselines for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_normal_baselines_owner_delete" on public.ba_normal_baselines for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_observations_owner_select" on public.ba_observations;
drop policy if exists "ba_observations_owner_insert" on public.ba_observations;
drop policy if exists "ba_observations_owner_update" on public.ba_observations;
drop policy if exists "ba_observations_owner_delete" on public.ba_observations;
create policy "ba_observations_owner_select" on public.ba_observations for select to authenticated using (auth.uid() = user_id);
create policy "ba_observations_owner_insert" on public.ba_observations for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_observations_owner_update" on public.ba_observations for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_observations_owner_delete" on public.ba_observations for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_body_map_markers_owner_select" on public.ba_body_map_markers;
drop policy if exists "ba_body_map_markers_owner_insert" on public.ba_body_map_markers;
drop policy if exists "ba_body_map_markers_owner_update" on public.ba_body_map_markers;
drop policy if exists "ba_body_map_markers_owner_delete" on public.ba_body_map_markers;
create policy "ba_body_map_markers_owner_select" on public.ba_body_map_markers for select to authenticated using (auth.uid() = user_id);
create policy "ba_body_map_markers_owner_insert" on public.ba_body_map_markers for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_body_map_markers_owner_update" on public.ba_body_map_markers for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_body_map_markers_owner_delete" on public.ba_body_map_markers for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_screenings_owner_select" on public.ba_screenings;
drop policy if exists "ba_screenings_owner_insert" on public.ba_screenings;
drop policy if exists "ba_screenings_owner_update" on public.ba_screenings;
drop policy if exists "ba_screenings_owner_delete" on public.ba_screenings;
create policy "ba_screenings_owner_select" on public.ba_screenings for select to authenticated using (auth.uid() = user_id);
create policy "ba_screenings_owner_insert" on public.ba_screenings for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_screenings_owner_update" on public.ba_screenings for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_screenings_owner_delete" on public.ba_screenings for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_appointments_owner_select" on public.ba_appointments;
drop policy if exists "ba_appointments_owner_insert" on public.ba_appointments;
drop policy if exists "ba_appointments_owner_update" on public.ba_appointments;
drop policy if exists "ba_appointments_owner_delete" on public.ba_appointments;
create policy "ba_appointments_owner_select" on public.ba_appointments for select to authenticated using (auth.uid() = user_id);
create policy "ba_appointments_owner_insert" on public.ba_appointments for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_appointments_owner_update" on public.ba_appointments for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_appointments_owner_delete" on public.ba_appointments for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_risk_notes_owner_select" on public.ba_risk_notes;
drop policy if exists "ba_risk_notes_owner_insert" on public.ba_risk_notes;
drop policy if exists "ba_risk_notes_owner_update" on public.ba_risk_notes;
drop policy if exists "ba_risk_notes_owner_delete" on public.ba_risk_notes;
create policy "ba_risk_notes_owner_select" on public.ba_risk_notes for select to authenticated using (auth.uid() = user_id);
create policy "ba_risk_notes_owner_insert" on public.ba_risk_notes for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_risk_notes_owner_update" on public.ba_risk_notes for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_risk_notes_owner_delete" on public.ba_risk_notes for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_doctor_prep_owner_select" on public.ba_doctor_prep;
drop policy if exists "ba_doctor_prep_owner_insert" on public.ba_doctor_prep;
drop policy if exists "ba_doctor_prep_owner_update" on public.ba_doctor_prep;
drop policy if exists "ba_doctor_prep_owner_delete" on public.ba_doctor_prep;
create policy "ba_doctor_prep_owner_select" on public.ba_doctor_prep for select to authenticated using (auth.uid() = user_id);
create policy "ba_doctor_prep_owner_insert" on public.ba_doctor_prep for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_doctor_prep_owner_update" on public.ba_doctor_prep for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_doctor_prep_owner_delete" on public.ba_doctor_prep for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_check_ins_owner_select" on public.ba_check_ins;
drop policy if exists "ba_check_ins_owner_insert" on public.ba_check_ins;
drop policy if exists "ba_check_ins_owner_update" on public.ba_check_ins;
drop policy if exists "ba_check_ins_owner_delete" on public.ba_check_ins;
create policy "ba_check_ins_owner_select" on public.ba_check_ins for select to authenticated using (auth.uid() = user_id);
create policy "ba_check_ins_owner_insert" on public.ba_check_ins for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_check_ins_owner_update" on public.ba_check_ins for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_check_ins_owner_delete" on public.ba_check_ins for delete to authenticated using (auth.uid() = user_id);
drop policy if exists "ba_vault_documents_owner_select" on public.ba_vault_documents;
drop policy if exists "ba_vault_documents_owner_insert" on public.ba_vault_documents;
drop policy if exists "ba_vault_documents_owner_update" on public.ba_vault_documents;
drop policy if exists "ba_vault_documents_owner_delete" on public.ba_vault_documents;
create policy "ba_vault_documents_owner_select" on public.ba_vault_documents for select to authenticated using (auth.uid() = user_id);
create policy "ba_vault_documents_owner_insert" on public.ba_vault_documents for insert to authenticated with check (auth.uid() = user_id);
create policy "ba_vault_documents_owner_update" on public.ba_vault_documents for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "ba_vault_documents_owner_delete" on public.ba_vault_documents for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "ba_education_public_read" on public.ba_education;
create policy "ba_education_public_read" on public.ba_education for select to anon, authenticated using (true);

-- Storage bucket private
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('ba-vault', 'ba-vault', false, 10485760, array['application/pdf','image/png','image/jpeg','image/webp'])
on conflict (id) do update set public = false, file_size_limit = 10485760, allowed_mime_types = array['application/pdf','image/png','image/jpeg','image/webp'];

drop policy if exists "ba_vault_owner_insert" on storage.objects;
drop policy if exists "ba_vault_owner_select" on storage.objects;
drop policy if exists "ba_vault_owner_update" on storage.objects;
drop policy if exists "ba_vault_owner_delete" on storage.objects;
create policy "ba_vault_owner_insert" on storage.objects for insert to authenticated with check (bucket_id = 'ba-vault' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "ba_vault_owner_select" on storage.objects for select to authenticated using (bucket_id = 'ba-vault' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "ba_vault_owner_update" on storage.objects for update to authenticated using (bucket_id = 'ba-vault' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "ba_vault_owner_delete" on storage.objects for delete to authenticated using (bucket_id = 'ba-vault' and (storage.foldername(name))[1] = auth.uid()::text);
